export const ALL_BOOK_REQUEST = "ALL_BOOK_REQUEST";
export const ALL_BOOK_SUCCESS = "ALL_BOOK_SUCCESS";
export const ALL_BOOK_FAIL = "ALL_BOOK_FAIL";

export const BOOK_DETAILS_REQUEST = "BOOK_DETAILS_REQUEST";
export const BOOK_DETAILS_SUCCESS = "BOOK_DETAILS_SUCCESS";
export const BOOK_DETAILS_FAIL = "BOOK_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
