export const ALL_BOOK_REQUEST = "ALL_BOOK_REQUEST";
export const ALL_BOOK_SUCCESS = "ALL_BOOK_SUCCESS";
export const ALL_BOOK_FAIL = "ALL_BOOK_FAIL";

export const ADMIN_BOOK_REQUEST = "ADMIN_BOOK_REQUEST";
export const ADMIN_BOOK_SUCCESS = "ADMIN_BOOK_SUCCESS";
export const ADMIN_BOOK_FAIL = "ADMIN_BOOK_FAIL";

export const NEW_BOOK_REQUEST = "NEW_BOOK_REQUEST";
export const NEW_BOOK_SUCCESS = "NEW_BOOK_SUCCESS";
export const NEW_BOOK_RESET = "NEW_BOOK_RESET";
export const NEW_BOOK_FAIL = "NEW_BOOK_FAIL";

export const UPDATE_BOOK_REQUEST = "UPDATE_BOOK_REQUEST";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";
export const UPDATE_BOOK_RESET = "UPDATE_BOOK_RESET";
export const UPDATE_BOOK_FAIL = "UPDATE_BOOK_FAIL";

export const DELETE_BOOK_REQUEST = "DELETE_BOOK_REQUEST";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_RESET = "DELETE_BOOK_RESET";
export const DELETE_BOOK_FAIL = "DELETE_BOOK_FAIL";

export const BOOK_DETAILS_REQUEST = "BOOK_DETAILS_REQUEST";
export const BOOK_DETAILS_SUCCESS = "BOOK_DETAILS_SUCCESS";
export const BOOK_DETAILS_FAIL = "BOOK_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
